### ISSUE TITLE
Feature Parity with VS Code & CLI

### ISSUE THREAD

**Issue by rhamzeh** [openfga/intellij-plugin#33]
- [ ] Validate Store File #28 
- [ ] Validate Modular Modules
- [ ] Base validations should not require the CLI
- [ ] Transformation should not require the CLI
- [ ] Allow running tests through the CLI and display the output inline (like e.g. running go test in Goland or npm test in Webstorm)
- [ ] Remove the define remote server for now
  Later we can re-add it and support features such as:
  - CRUD stores
  - Allow deploying model to a selected remote defined servers + store
  - Allow data import/export
  - Data visualization
  - Query visualization
